# -*- coding: utf-8 -*-
"""sample_PYML_PAPER.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MJUIZvKJyibwRfbo13caPgTKUO1_bpuo
"""

# 1.
# Install required packages quietly (no extra output)
!pip install transformers optuna lime shap seaborn scikit-learn --quiet

# Core libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud

# PyTorch + Transformers for NLP model
import torch
from torch.utils.data import Dataset, DataLoader
from transformers import DistilBertTokenizerFast, DistilBertForSequenceClassification
from torch.optim import AdamW

# Scikit-learn for preprocessing and evaluation
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score

# Optuna for hyperparameter tuning
import optuna
from optuna.pruners import MedianPruner

# Use GPU if available, otherwise fallback to CPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# 2.
from google.colab import files
import io

# Upload file from local system to Colab
uploaded = files.upload()
file_name = next(iter(uploaded.keys()))

# Read Excel or CSV based on file extension
if file_name.endswith('.xlsx'):
    df = pd.read_excel(io.BytesIO(uploaded[file_name]))
else:
    df = pd.read_csv(io.StringIO(uploaded[file_name].decode('utf-8')))

# Keep only the required label categories
required_labels = ["not_cyberbullying", "age", "gender", "ethnicity", "religion"]
df = df[df["cyberbullying_type"].isin(required_labels)]

# 3.
import re

# Function to clean tweets: lowercase, remove URLs, mentions, hashtags, punctuation, numbers
def clean_text(text):
    text = text.lower()
    text = re.sub(r'http\S+', '', text)         # remove URLs
    text = re.sub(r'@\w+', '', text)            # remove @mentions
    text = re.sub(r'#\w+', '', text)            # remove hashtags
    text = re.sub(r'[^\w\s]', '', text)         # remove punctuation/emojis
    text = re.sub(r'\d+', '', text)             # remove numbers
    text = re.sub(r'\s+', ' ', text).strip()    # remove extra spaces
    return text

# Apply text cleaning to tweet column
df['tweet_text'] = df['tweet_text'].apply(clean_text)

# Calculate tweet length for analysis
df['tweet_length'] = df['tweet_text'].apply(len)

# Plot: Tweet length distribution
plt.figure(figsize=(8, 4))
sns.histplot(df['tweet_length'], bins=50, kde=True)
plt.title('Distribution of Tweet Lengths')
plt.xlabel('Tweet Length')
plt.ylabel('Frequency')
plt.show()

# Plot: Distribution of labels
plt.figure(figsize=(8,5))
sns.countplot(x='cyberbullying_type', data=df)
plt.title("Distribution of Cyberbullying Types (5 Classes)")
plt.xticks(rotation=45)
plt.show()

# Generate and display WordCloud for all tweets
text = " ".join(df['tweet_text'].tolist())
wordcloud = WordCloud(width=800, height=400, background_color='white').generate(text)
plt.figure(figsize=(8,5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.show()

# 4.
# Merge multi-class labels into binary (cyberbullying / not_cyberbullying)
df['cyberbullying_binary'] = df['cyberbullying_type'].apply(
    lambda x: 'not_cyberbullying' if x == 'not_cyberbullying' else 'cyberbullying'
)

# Encode binary labels as integers (0 = cyberbullying, 1 = not_cyberbullying)
le = LabelEncoder()
df['label'] = le.fit_transform(df['cyberbullying_binary'])

# Show distribution of binary labels
print("Binary distribution:\n", df['cyberbullying_binary'].value_counts())

# Split into training and validation sets (stratified to keep label balance)
train_texts, val_texts, train_labels, val_labels = train_test_split(
    df['tweet_text'], df['label'], test_size=0.2, random_state=42, stratify=df['label']
)

# 5.
# Load DistilBERT tokenizer (uncased version)
tokenizer = DistilBertTokenizerFast.from_pretrained('distilbert-base-uncased')

# Tokenize text sequences into input IDs & attention masks
def tokenize_texts(texts):
    return tokenizer(
        list(texts),
        truncation=True,      # cut off longer texts
        padding=True,         # pad shorter texts
        max_length=128,       # fixed sequence length
        return_tensors='pt'   # return as PyTorch tensors
    )

# Custom PyTorch dataset for tokenized tweets
class BullyDataset(Dataset):
    def __init__(self, tokens, labels):
        self.tokens = tokens
        self.labels = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return {
            'input_ids': self.tokens['input_ids'][idx],
            'attention_mask': self.tokens['attention_mask'][idx],
            'labels': torch.tensor(self.labels[idx], dtype=torch.long)
        }

# 6.
# Optuna objective function for hyperparameter tuning (with pruning)
def objective(trial):
    # Suggest hyperparameters
    learning_rate = trial.suggest_categorical("lr", [1e-5, 3e-5, 5e-5])
    batch_size = trial.suggest_categorical("batch_size", [8, 16, 32])
    epochs = trial.suggest_int("epochs", 2, 4)

    # Tokenize train/validation data
    train_tokens = tokenize_texts(train_texts)
    val_tokens = tokenize_texts(val_texts)

    # Wrap into PyTorch datasets and loaders
    train_dataset = BullyDataset(train_tokens, list(train_labels))
    val_dataset = BullyDataset(val_tokens, list(val_labels))
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=batch_size)

    # Load model for binary classification
    model = DistilBertForSequenceClassification.from_pretrained(
        "distilbert-base-uncased",
        num_labels=2
    ).to(device)

    optimizer = AdamW(model.parameters(), lr=learning_rate)
    loss_fn = torch.nn.CrossEntropyLoss()

    # Training loop
    for epoch in range(epochs):
        model.train()
        for batch in train_loader:
            optimizer.zero_grad()
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['labels'].to(device)

            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            loss = loss_fn(outputs.logits, labels)
            loss.backward()
            optimizer.step()

        # Validation phase
        model.eval()
        preds, truths = [], []
        with torch.no_grad():
            for batch in val_loader:
                input_ids = batch['input_ids'].to(device)
                attention_mask = batch['attention_mask'].to(device)
                labels = batch['labels'].to(device)

                outputs = model(input_ids=input_ids, attention_mask=attention_mask)
                predictions = torch.argmax(torch.softmax(outputs.logits, dim=1), dim=1)

                preds.extend(predictions.cpu().numpy())
                truths.extend(labels.cpu().numpy())

        f1 = f1_score(truths, preds)  # main metric

        # Report progress to Optuna & prune if needed
        trial.report(f1, epoch)
        if trial.should_prune():
            raise optuna.TrialPruned()

    return f1

# Create Optuna study to maximize F1 score (with pruning for faster runs)
study = optuna.create_study(direction="maximize", pruner=MedianPruner(n_warmup_steps=1))

# Run hyperparameter search (increase n_trials for better tuning if time allows)
study.optimize(objective, n_trials=7)

# Show best hyperparameters found
print("Best Hyperparameters:", study.best_trial.params)
best_params = study.best_trial.params

# 7.
from transformers import DistilBertConfig

# Re-tokenize and recreate DataLoaders using best Optuna parameters
train_tokens = tokenize_texts(train_texts)
val_tokens = tokenize_texts(val_texts)
train_dataset = BullyDataset(train_tokens, list(train_labels))
val_dataset = BullyDataset(val_tokens, list(val_labels))
train_loader = DataLoader(train_dataset, batch_size=best_params['batch_size'], shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=best_params['batch_size'])

# Configure model with extra dropout for regularization
config = DistilBertConfig.from_pretrained(
    "distilbert-base-uncased",
    num_labels=2,
    dropout=0.3,            # dropout on hidden layers
    attention_dropout=0.3   # dropout on attention layers
)

# Load model with custom config
model = DistilBertForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    config=config
).to(device)

# Optimizer with weight decay for better generalization
optimizer = AdamW(model.parameters(), lr=best_params['lr'], weight_decay=0.01)
loss_fn = torch.nn.CrossEntropyLoss()

# Early stopping setup
patience = 2
best_val_loss = float('inf')
epochs_no_improve = 0

# Track metrics over time
train_acc_history, val_acc_history = [], []
train_loss_history, val_loss_history = [], []

# Train for up to best_params['epochs'] (early stopping may halt earlier)
for epoch in range(best_params['epochs']):
    # ----- Training -----
    model.train()
    total_train_loss, correct_train, total_train = 0, 0, 0

    for batch in train_loader:
        optimizer.zero_grad()
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)

        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        loss = loss_fn(outputs.logits, labels)
        loss.backward()
        optimizer.step()

# 8.
# Plot accuracy curves
plt.figure(figsize=(4, 2))
plt.plot(train_acc_history, label='Train Accuracy')
plt.plot(val_acc_history, label='Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.title('Training vs Validation Accuracy')
plt.legend()
plt.show()

# Plot loss curves
plt.figure(figsize=(4, 2))
plt.plot(train_loss_history, label='Train Loss')
plt.plot(val_loss_history, label='Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Training vs Validation Loss')
plt.legend()
plt.show()

# 9.
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix, classification_report, roc_auc_score, roc_curve
)
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# Load best model weights (saved during training)
model.load_state_dict(torch.load("best_model.pth"))
model.eval()

# Function to compute predictions, probabilities, and evaluation metrics
def get_metrics(data_loader):
    preds, truths, probs = [], [], []
    with torch.no_grad():
        for batch in data_loader:
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['labels'].to(device)

            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            softmax_probs = torch.softmax(outputs.logits, dim=1)
            predictions = torch.argmax(softmax_probs, dim=1)

            preds.extend(predictions.cpu().numpy())
            truths.extend(labels.cpu().numpy())
            probs.extend(softmax_probs[:, 1].cpu().numpy())  # probability for class 1

    preds, truths, probs = np.array(preds), np.array(truths), np.array(probs)
    metrics = {
        "accuracy": accuracy_score(truths, preds),
        "precision": precision_score(truths, preds),
        "recall": recall_score(truths, preds),
        "f1_macro": f1_score(truths, preds, average='macro'),
        "f1_weighted": f1_score(truths, preds, average='weighted'),
        "roc_auc": roc_auc_score(truths, probs),
        "preds": preds,
        "truths": truths,
        "probs": probs
    }
    return metrics

# Get metrics for both train and validation sets
train_metrics = get_metrics(train_loader)
val_metrics = get_metrics(val_loader)

# Print validation performance summary
print(f"Accuracy: {val_metrics['accuracy']:.4f}")
print(f"Precision: {val_metrics['precision']:.4f}")
print(f"Recall: {val_metrics['recall']:.4f}")
print(f"Macro F1-score: {val_metrics['f1_macro']:.4f}")
print(f"Weighted F1-score: {val_metrics['f1_weighted']:.4f}")
print(f"ROC AUC: {val_metrics['roc_auc']:.4f}\n")
print("Classification Report:\n",
      classification_report(val_metrics["truths"], val_metrics["preds"], target_names=le.classes_))

# Confusion matrix (percent form)
cm = confusion_matrix(val_metrics["truths"], val_metrics["preds"])
cm_percent = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis] * 100
plt.figure(figsize=(6, 5))
sns.heatmap(cm_percent, annot=True, fmt='.1f', cmap='Blues',
            xticklabels=le.classes_, yticklabels=le.classes_)
plt.title("Confusion Matrix (%) - Validation")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# ROC curve
fpr, tpr, _ = roc_curve(val_metrics["truths"], val_metrics["probs"])
plt.figure(figsize=(7, 5))
plt.plot(fpr, tpr, label=f"AUC = {val_metrics['roc_auc']:.2f}")
plt.plot([0, 1], [0, 1], linestyle='--', color='gray')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve - Validation')
plt.legend()
plt.show()

# Quick overfitting check
print("\n=== Overfitting Check ===")
for metric in ["accuracy", "roc_auc", "f1_macro"]:
    gap = train_metrics[metric] - val_metrics[metric]
    if gap > 0.1:  # >10% gap → potential overfitting
        print(f"⚠️ Possible overfitting detected on {metric} (gap={gap:.2f})")
    else:
        print(f"✅ No significant overfitting on {metric} (gap={gap:.2f})")

"""**LIME**"""

# Import required libraries
from lime.lime_text import LimeTextExplainer
from collections import Counter
from IPython.display import display
import os, numpy as np, matplotlib.pyplot as plt, seaborn as sns

# ---- Settings ----
os.makedirs("lime_outputs", exist_ok=True)  # Create folder to store HTML explanations
explainer = LimeTextExplainer(
    class_names=list(le.classes_),  # Class names from your LabelEncoder
    random_state=42                 # For reproducibility
)

# Ensure validation texts and labels have clean index 0..n-1
texts = val_texts.reset_index(drop=True)
labels_series = val_labels.reset_index(drop=True)

# Define a prediction function for LIME
# It takes a list of texts, tokenizes them, passes them to the model,
# and returns probabilities (n_samples x n_classes)
def predict_proba_fn(texts_list):
    model.eval()  # Set model in evaluation mode
    toks = tokenizer(
        list(texts_list),
        truncation=True,
        padding=True,
        max_length=128,
        return_tensors='pt'
    )
    toks = {k: v.to(device) for k, v in toks.items()}  # Move tensors to GPU/CPU
    with torch.no_grad():  # Disable gradient calculation for faster inference
        outputs = model(**toks)
        probs = torch.softmax(outputs.logits, dim=1).cpu().numpy()
    return probs

# Number of samples from validation set to explain
N = 50
N = min(N, len(texts))  # Ensure we don't sample more than available
np.random.seed(42)      # For reproducibility
sample_indices = np.random.choice(len(texts), N, replace=False)  # Randomly pick indices

# Aggregators for analysis:
# freq_counter — how many times each word appears as a positive contributor
# weighted_counter — sum of contribution weights across samples
freq_counter = Counter()
weighted_counter = Counter()

# Identify index of 'cyberbullying' class from LabelEncoder
target_label_name = 'cyberbullying'
if target_label_name in list(le.classes_):
    target_label_index = int(np.where(le.classes_ == target_label_name)[0][0])
else:
    target_label_index = 0  # Fallback if not found

print(f"Explaining N={N} samples from validation set. Target class '{target_label_name}' index = {target_label_index}")

# Loop through selected samples
for i, idx in enumerate(sample_indices):
    tweet = texts.iloc[idx]                     # The tweet text
    true_idx = int(labels_series.iloc[idx])     # True label index
    true_name = le.inverse_transform([true_idx])[0]  # True label name

    probs = predict_proba_fn([tweet])[0]        # Get prediction probabilities
    pred_idx = int(np.argmax(probs))            # Predicted label index
    pred_name = le.inverse_transform([pred_idx])[0]  # Predicted label name

    # LIME explanation for target class (cyberbullying)
    exp = explainer.explain_instance(
        tweet,
        predict_proba_fn,
        labels=(target_label_index,),  # Only explain for cyberbullying class
        num_features=15,               # Top 15 words in explanation
        num_samples=2000               # Number of perturbed samples LIME will generate
    )

    # Save explanation as HTML for later inspection
    html_path = f"lime_outputs/lime_explanation_sample{i+1}_idx{idx}.html"
    exp.save_to_file(html_path)

    # Collect words with positive contribution towards cyberbullying class
    for word, weight in exp.as_list(label=target_label_index):
        if weight > 0:  # Only count words that increase cyberbullying probability
            freq_counter[word] += 1
            weighted_counter[word] += weight

    # Display first 5 explanations in notebook for quick inspection
    if i < 5:
        print(f"\n[{i+1}/{N}] idx={idx} true={true_name} pred={pred_name} probs={probs}")
        display(exp.show_in_notebook(text=True))
    else:
        # For the rest, just print progress
        if (i+1) % 10 == 0 or i == N-1:
            print(f"[{i+1}/{N}] processed, saved: {html_path}")

# ---- Plot top words by frequency ----
top_k = 25
top_freq = freq_counter.most_common(top_k)
if top_freq:
    words, counts = zip(*top_freq)
    plt.figure(figsize=(8,8))
    sns.barplot(x=list(counts), y=list(words))
    plt.title(f"Top {len(words)} words — frequency in LIME top-features (N={N})")
    plt.xlabel("Count (appeared as positive contributor)")
    plt.tight_layout()
    plt.show()
else:
    print("No positive tokens collected in freq_counter — check num_features / samples or class label.")

# ---- Plot top words by summed positive weights ----
top_weights = weighted_counter.most_common(top_k)
if top_weights:
    words_w, weights = zip(*top_weights)
    plt.figure(figsize=(8,8))
    sns.barplot(x=list(weights), y=list(words_w))
    plt.title(f"Top {len(words_w)} words — sum of LIME positive weights (N={N})")
    plt.xlabel("Sum of LIME weights (positive contributions)")
    plt.tight_layout()
    plt.show()
else:
    print("No tokens collected in weighted_counter — check parameters.")

"""**SHAP**"""

import shap
import numpy as np
import torch
import matplotlib.pyplot as plt

# Check if we can use a GPU, otherwise stick to CPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

# A helper for SHAP that takes token IDs, runs them through the model,
# and returns the probability of the "cyberbullying" class (index 1 here)
def pred_on_token_ids(token_id_array):
    input_ids = torch.tensor(token_id_array, dtype=torch.long).to(device)
    attention_mask = (input_ids != tokenizer.pad_token_id).long().to(device)  # mask out padding tokens
    model.eval()
    with torch.no_grad():
        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        probs = torch.softmax(outputs.logits, dim=1)[:, 1].cpu().numpy()
    return probs

# Pick 10 random validation texts as a "reference" set for SHAP to compare against
background_texts = val_texts.sample(10, random_state=42).tolist()
background_tokens = tokenizer(
    background_texts, truncation=True, padding='max_length',
    max_length=128, return_tensors='np'
)
background_input_ids = background_tokens['input_ids']

# Create the SHAP KernelExplainer using our prediction function and reference examples
explainer = shap.KernelExplainer(pred_on_token_ids, background_input_ids)

# Select 50 random validation texts we actually want to explain
test_texts = val_texts.sample(50, random_state=42).tolist()
test_tokens = tokenizer(
    test_texts, truncation=True, padding='max_length',
    max_length=128, return_tensors='np'
)
test_input_ids = test_tokens['input_ids']

# Compute SHAP values in small batches so we don’t run out of memory
batch_size = 5
all_shap_values = []
for i in range(0, len(test_input_ids), batch_size):
    batch_ids = test_input_ids[i:i+batch_size]
    shap_vals_batch = explainer.shap_values(batch_ids, nsamples=100)
    all_shap_values.append(shap_vals_batch)

# Combine all the batches into one array
shap_values = np.vstack(all_shap_values)

# Convert the first set of token IDs back into readable tokens
feature_names = tokenizer.convert_ids_to_tokens(test_input_ids[0])

# Show a summary plot to see which tokens were most influential overall
plt.figure()
shap.summary_plot(shap_values, features=test_input_ids,
                  feature_names=feature_names, max_display=15)
plt.show()

# Show the same thing as a bar chart instead of a scatter plot
plt.figure()
shap.summary_plot(shap_values, features=test_input_ids,
                  feature_names=feature_names, plot_type="bar")
plt.show()

# Create a force plot for just the first example to see token-by-token influence
shap.force_plot(
    explainer.expected_value,
    shap_values[0],
    tokenizer.convert_ids_to_tokens(test_input_ids[0]),
    matplotlib=True
)
plt.show()

# ---- Force Plot (fourth sample) ----

# ✅ Print the tweet text from your DataFrame
print("Tweet text:", test_texts[4])

shap.force_plot(
    explainer.expected_value,
    shap_values[4],
    tokenizer.convert_ids_to_tokens(test_input_ids[4]),
    matplotlib=True
)
plt.show()

import torch, gc

#del model  if you no longer need it
del explainer, shap_values  # or any other large vars
gc.collect()
torch.cuda.empty_cache()

import pandas as pd
import matplotlib.pyplot as plt

from google.colab import files
import io

# Upload file from local system to Colab
uploaded = files.upload()
file_name = next(iter(uploaded.keys()))

# Read Excel or CSV based on file extension
if file_name.endswith('.xlsx'):
    data = pd.read_excel(io.BytesIO(uploaded[file_name]))
else:
    data = pd.read_csv(io.StringIO(uploaded[file_name].decode('utf-8')))

# Keep only the required label categories
required_labels = ["not_cyberbullying", "age", "gender", "ethnicity", "religion"]
data = data[data["cyberbullying_type"].isin(required_labels)]

tweet_counts = data.groupby(data.index // 100).size()

plt.figure(figsize=(8,5))
plt.plot(tweet_counts.index, tweet_counts.values, marker="o")
plt.title("Number of Tweets per 100 Rows")
plt.xlabel("Batch of 100 Tweets")
plt.ylabel("Count")
plt.grid(True)
plt.show()

cumulative_counts = data["cyberbullying_type"].value_counts().cumsum()

plt.figure(figsize=(8,5))
plt.plot(cumulative_counts.index, cumulative_counts.values, marker="o")
plt.title("Cumulative Count of Tweets by Type")
plt.xlabel("Cyberbullying Type")
plt.ylabel("Cumulative Count")
plt.grid(True)
plt.show()

data["tweet_length"] = data["tweet_text"].astype(str).apply(len)

plt.figure(figsize=(8,5))
plt.plot(data.index, data["tweet_length"], alpha=0.5)
plt.title("Tweet Length Trend Across Dataset")
plt.xlabel("Tweet Index")
plt.ylabel("Tweet Length (characters)")
plt.grid(True)
plt.show()

avg_length_per_class = data.groupby("cyberbullying_type")["tweet_length"].mean()

plt.figure(figsize=(8,5))
plt.plot(avg_length_per_class.index, avg_length_per_class.values, marker="o")
plt.title("Average Tweet Length per Cyberbullying Type")
plt.xlabel("Cyberbullying Type")
plt.ylabel("Average Length")
plt.grid(True)
plt.show()